server:
  port: 9090
  http2:
    enabled: true
spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    core:
      master:
        hikari:
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          jdbc-url: {jdbc url}
          username: {username}
          password: '{password}'
          maximum-pool-size: 5 # 최대 커넥션 풀 크기
          minimum-idle: 2 # 최소 유휴 커넥션 수
          idle-timeout: 300000 # 유휴 커넥션 유지 시간: 5분
          connection-timeout: 30000 # 커넥션 요청 대기시간: 30초
          max-lifetime: 1800000 # 커넥션 최대 수명: 30분
      slave:
        hikari:
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          jdbc-url: {jdbc url}
          username: {username}
          password: '{password}'
          maximum-pool-size: 5 # 최대 커넥션 풀 크기
          minimum-idle: 2 # 최소 유휴 커넥션 수
          idle-timeout: 300000 # 유휴 커넥션 유지 시간: 5분
          connection-timeout: 30000 # 커넥션 요청 대기시간: 30초
          max-lifetime: 1800000 # 커넥션 최대 수명: 30분


common:
  encrypt:
    key: "{{암복호화키}}"
    salt: "{{암호화키}}"

logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO
      connection : OFF
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS z,Asia/Seoul
