server:
  port: 9090
  http2:
    enabled: true
spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB

logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO
      connection : OFF
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS z,Asia/Seoul
